baseURL = "https://curry.girigiribauer.com/"
languageCode = "ja-jp"
title = "お昼に何食べるか考えるのつらい ご当地カレーが食べたい！"
theme = "curry"
hasCJKLanguage = true
Paginate = 100
preserveTaxonomyNames = true
EnableGitInfo = false
pluralizelisttitles = false
googleAnalytics = "UA-36767095-3"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "sitemap"]
enableEmoji = true

[permalinks]
post = "/:filename/"

[params]
author = "girigiribauer"
description = "ご当地カレーを食べよう！といいつつ、全国各地を妄想旅（リアル旅）しながら、おいしいご当地カレーを探していくご当地カレーブログ！"

[markup.goldmark.renderer]
unsafe = true

[build.environment]
HUGO_VERSION = "0.69.2"
